### ISSUE TITLE
"dict" type in "def GetVideo" issue

### ISSUE THREAD

**Issue by NelsonGL** [c-rainbow/twitch-chat-analyzer-py#6]
Was installing the library and getting some "type" error in function "Get Video" after some research I found that in some python new versions the "dict" type is "object", checked that and found the problem

>>> type(dict)
<class 'type'>

Changed to capital D and worked: 

>>> type(Dict)
<class 'typing._GenericAlias'>

**Comment by c-rainbow** [comment]
Thanks for the report. Fixed with https://github.com/c-rainbow/twitch-chat-analyzer-py/pull/5
